files:
  - source: /src/main/resources/assets/narutomod/lang/en_us.json
    translation: /src/main/resources/assets/narutomod/lang/%locale_with_underscore%.json
commit_message: "lang: Translations %locale_with_underscore% from Crowdin"
append_commit_message: false
