on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    # https://github.com/google-github-actions/release-please-action in case more config is needed
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          # See how to configure file https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
      # See output info at https://github.com/google-github-actions/release-please-action#configuration for variables
      - name: Build and publish (release)
        if: ${{ steps.release.outputs.release_created }}
        env:
          CURSE_API: ${{ secrets.CURSE_API }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          IS_RELEASE: ${{ steps.release.outputs.release_created }}
        run: |
          # Build
          ./gradlew build discordupload curseforge
