on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    # https://github.com/google-github-actions/release-please-action in case more config is needed
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          # See how to configure file https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
      # See output info at https://github.com/google-github-actions/release-please-action#configuration for variables
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up JDK 17
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Download MC assets
        run: ./gradlew downloadAssets || ./gradlew downloadAssets || (sleep 30s && ./gradlew downloadAssets)
      - name: Run DataGen
        run: ./gradlew runData
      - name: Build and upload preview (run for non-release builds)
        if: ${{ !steps.release.outputs.release_created }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Build
          ./gradlew build discordupload
      - name: Build and publish (release)
        if: ${{ steps.release.outputs.release_created }}
        env:
          CURSE_API: ${{ secrets.CURSE_API }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Build
          ./gradlew build discordupload curseforge
